# Generated by Django 4.1.7 on 2026-03-17 01:57

import bson.objectid
from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', djongo.models.fields.ObjectIdField(auto_created=True, default=bson.objectid.ObjectId, editable=False, primary_key=True, serialize=False)),
                ('user_email', models.EmailField(max_length=254)),
                ('hero_alias', models.CharField(max_length=120)),
                ('activity_type', models.CharField(max_length=120)),
                ('duration_minutes', models.IntegerField()),
                ('calories_burned', models.IntegerField()),
                ('performed_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'activities',
                'ordering': ['-performed_at'],
            },
        ),
        migrations.CreateModel(
            name='LeaderboardEntry',
            fields=[
                ('id', djongo.models.fields.ObjectIdField(auto_created=True, default=bson.objectid.ObjectId, editable=False, primary_key=True, serialize=False)),
                ('hero_alias', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('team_name', models.CharField(max_length=100)),
                ('score', models.IntegerField()),
                ('rank', models.IntegerField()),
                ('streak_days', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'leaderboard',
                'ordering': ['rank', '-score'],
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', djongo.models.fields.ObjectIdField(auto_created=True, default=bson.objectid.ObjectId, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('city', models.CharField(max_length=100)),
                ('motto', models.CharField(max_length=255)),
                ('total_points', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'teams',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', djongo.models.fields.ObjectIdField(auto_created=True, default=bson.objectid.ObjectId, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=120)),
                ('hero_alias', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('team_name', models.CharField(max_length=100)),
                ('favorite_workout', models.CharField(max_length=120)),
                ('points', models.IntegerField(default=0)),
                ('joined_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'users',
                'ordering': ['hero_alias'],
            },
        ),
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', djongo.models.fields.ObjectIdField(auto_created=True, default=bson.objectid.ObjectId, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=120)),
                ('hero_alias', models.CharField(max_length=120)),
                ('recommended_team', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=120)),
                ('intensity', models.CharField(max_length=50)),
                ('duration_minutes', models.IntegerField()),
                ('description', models.TextField()),
            ],
            options={
                'db_table': 'workouts',
                'ordering': ['title'],
            },
        ),
    ]
